### PR TITLE
Feature/tdd-project

### PR DESCRIPTION
**Pull request by ClaudiaRojasSoto**
# Description:
This Pull Request aims to merge the complete implementation of the Solver class, which includes methods for calculating the factorial of a number (factorial), reversing a string (reverse), and applying the FizzBuzz logic (fizzbuzz). The development of this feature has been performed following the principles of Test-Driven Development (TDD).

> I have been given permission by the Student Success team to work solo this week. If you have any questions please reach out to Marco Lizza via the Code Reviewers Slack workspace.

## General Requirements Met:
- [x] No linter errors.
- [x] Correct Gitflow used.
- [x] Professionally documented code and workflow.

### Specific Ruby Requirements:
- [x] Follow established best practices for Ruby.

### Project Requirements:
- [x] Create a class called Solver.
- [x] Implement a factorial method that takes an integer argument and returns its factorial.
- [x] A Special case of factorial of 0 is handled.
- [x] An exception is raised for negative integers.
- [x] Implement a reverse method that takes a string and returns it reversed.
- [x] Implement a fizzbuzz method that takes an integer argument and returns a string as per the FizzBuzz rules.

### Commit History:
The commit history demonstrates that the TDD methodology has been followed, starting with writing tests and then proceeding with the implementation.

#### Tests:
All unit tests have passed successfully, validating that each method meets the specified requirements.

#### How to Test the Changes:

- Clone the feature branch.
- Run `ruby solver_test.rb`.

Kindly ask for a review of this implementation to validate that the requirements and best practices have been met before merging with develop.
greetings,
@ClaudiaRojasSoto

### CODE REVIEW

**Review by Strangeal — COMMENTED** [review]
Hi @ClaudiaRojasSoto, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- [ ] It appears that the project was intended to be completed using pair programming. However, based on the commit history, it seems that you completed the project alone instead of collaborating with your coding partner. For the purpose of maintaining the integrity of the pair programming process, I kindly request you to reach out to your coding partner and work together on the project before resubmitting it for review.  
   - In case you encountered any difficulties or issues with your coding partner that prevented you from collaborating, I encourage you to contact Student Success ([Success@microverse.org](mailto:Success@microverse.org)) to address the situation and seek assistance. It's important to adhere to the principles of pair programming and communicate any challenges you may face in order to ensure a fair and effective learning environment.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by ClaudiaRojasSoto** [comment]
@Strangeal I wrote some lines from Marco Lizza on my Pull Request...
I am sharing with you of a picture of my Pull request with a comment about it.

Captura de pantalla 2023-09-06 a la(s) 19 51 16

**Comment by ClaudiaRojasSoto** [comment]
@Strangeal ...
Captura de pantalla 2023-09-06 a la(s) 19 56 10

**Review by sumairq — APPROVED** [review]
### Hi @ClaudiaRojasSoto , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✔️ Good commit history
✔️Linters are passing
✔️Very professional README
✔️Correct Git flow
✔️Descriptive PR
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
